name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      fail-fast: false
      matrix:
        task: [test, format, clippy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore cache
        uses: Swatinem/rust-cache@v2
      - name: Install target
        run: rustup target add wasm32-unknown-unknown

      - name: Run task
        run: |
          if [ "${{ matrix.task }}" == "test" ]; then
            cargo test --all
          elif [ "${{ matrix.task }}" == "format" ]; then
            cargo fmt --all -- --check
          elif [ "${{ matrix.task }}" == "clippy" ]; then
            cargo clippy --all -- -D warnings
          fi
