name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      fail-fast: false
      matrix:
        task: [test, format, clippy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore cache
        uses: Swatinem/rust-cache@v2
      - name: Install target
        run: rustup target add wasm32-unknown-unknown

      - if: matrix.task == 'test'
        run: cargo test --all
      - if: matrix.task == 'format'
        run: cargo fmt --all -- --check
      - if: matrix.task == 'clippy'
        run: cargo clippy --all -- -D warnings
